### ISSUE TITLE
Wires

### ISSUE THREAD

**Issue by raaavioli** [raaavioli/Connected#3]
Enable selecting two objects and connect a wire between them.
 
 How the actual implementation works is left for investigation by @steenish. 
 
 ### Suggestions
 - Select first object -> "Add wire" -> (Wire created attached to first object) -> Select other object -> "Attach wire" -> Objects connected
 - Select first object -> Select other object simultaneously -> "Connect objects" -> Objects connected

**Comment by steenish** [comment]
I think moving the ends of the wires using your hands should be part of the interaction, I think you lose an entire aspect of the thing if you "select" objects and just choose that they should be connected.

So far, I have been able to do this
![wireSimulated](https://user-images.githubusercontent.com/26511631/141701620-ad410306-a5c1-4e80-aa97-27fbfafed9e8.gif)
and I think it would be best if one has to pull the ends of the wires to the connection points to connect them. The colors of the wire ends match the colors that the connection points usually have on electrical components, to make the connections and the direction of the current more intuitive to the player.

**Comment by raaavioli** [comment]
> I think moving the ends of the wires using your hands should be part of the interaction, I think you lose an entire aspect of the thing if you "select" objects and just choose that they should be connected.
> 
> So far, I have been able to do this ![wireSimulated](https://user-images.githubusercontent.com/26511631/141701620-ad410306-a5c1-4e80-aa97-27fbfafed9e8.gif) and I think it would be best if one has to pull the ends of the wires to the connection points to connect them. The colors of the wire ends match the colors that the connection points usually have on electrical components, to make the connections and the direction of the current more intuitive to the player.

This is more or less what I imagined with my first suggestion. When you ”select” the first object and start adding a wire, the wire can as you suggest follow the cursor/hands of the player to the second object that is selected. 

But as you say, it may be the most intuitive and fun to take an end of a wire from say the workbench, pull that to the first component, then pull the other end to the second component. 

Looks great :)

**Comment by steenish** [comment]
Left to do now (probably):
- [x] make animated shader when wire is connected
- [x] make connectors on the ends of the wire
- [ ] interface the wire code with the component code
